[tool.poetry]
name = "dowhy"
version = "0.8.0"
description = "DoWhy is a Python library for causal inference that supports explicit modeling and testing of causal assumptions"
authors = [
    "Amit Sharma <amshar@microsoft.com>",
    "Emre Kiciman <emrek@microsoft.com>"
]
maintainers = []
license = "MIT"
documentation = "https://py-why.github.io/dowhy"
repository = "https://github.com/pywhy/dowhy"
classifiers = [  
    'Development Status :: 4 - Beta',
    'License :: OSI Approved :: MIT License',
    'Programming Language :: Python :: 3.6',
    'Programming Language :: Python :: 3.7',
    'Programming Language :: Python :: 3.8',
    'Programming Language :: Python :: 3.9',
]
keywords = [
    'causality',
    'machine-learning',
    'causal-inference',
    'statistics',
    'graphical-model'
]
exclude = ['docs', 'test']
readme = 'README.rst'

[tool.poetry.dependencies]
python = ">=3.8,<3.11"
scipy = "^1.8.1"
statsmodels = "^0.13.2"
numpy = "^1.23.1"
pandas = "^1.4.3"
networkx = "^2.8.5"
sympy = "^1.10.1"
scikit-learn = "1.0.2"
pydot = "^1.4.2"
joblib = "^1.1.0"
pandas-stubs = "^1.4.3"
matplotlib = {version = "^3.5.2", optional = true}

[tool.poetry.extras]
plotting = ['matplotlib']

[tool.poetry.dev-dependencies]
poethepoet = "^0.16.0"
flake8 = "^4.0.1"
black = "^22.6.0"
isort = "^5.10.1"
pytest = "^7.1.2"
twine = "^4.0.1"
nbformat = "^5.4.0"
jupyter = "^1.0.0"
flaky = "^3.7.0"
pygraphviz = "^1.9"
causalml = "^0.12.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = [
    "advanced: not be to run each time. only on package updates."
]

[tool.poe.tasks]
# stop the build if there are Python syntax errors or undefined names
_flake8Errors = "flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics"
_flake8Warnings = "flake8 . --count --exit-zero --statistics"
_black = 'black .'
_isort = 'isort .'
_preparePackage = "python setup.py check sdist bdist_wheel"
_twine = "twine check dist/*"

test = "pytest -v -m \"not advanced\""

[tool.poe.tasks.verifyPackage]
sequence = ['_preparePackage', '_twine']
ignore_fail = 'return_non_zero'

# TODO: add formatting to build process
[tool.poe.tasks.format]
sequence = ['_black', '_isort']
ignore_fail = 'return_non_zero'

[tool.poe.tasks.lint]
sequence = ['_flake8Errors', '_flake8Warnings']
ignore_fail = 'return_non_zero'

[tool.poe.tasks.verify]
sequence = ['lint', 'test']
ignore_fail = "return_non_zero"
