name: build-and-publish-docs
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install graphviz
        run: |
          sudo apt install graphviz libgraphviz-dev graphviz-dev pkg-config pandoc
        
      - uses: Jimver/cuda-toolkit@v0.2.8
        id: cuda-toolkit
        with:
          cuda: '11.7.0'

      - name: Set up R (required for rpy2)
        uses: r-lib/actions/setup-r@v2
        
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      
      - name: Install Poetry 1.1.14
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: '1.1.14'
      
      - uses: actions/checkout@main
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Install R Dependencies
        run: |
          Rscript -e 'install.packages("BiocManager")'
          Rscript -e 'BiocManager::install(c("bnlearn", "pcalg", "kpcalg"))'
          Rscript -e 'install.packages("Rcpp", repos="http://cran.us.r-project.org")'
          Rscript -e 'install.packages("Matching", repos="http://cran.us.r-project.org")'
          Rscript -e 'install.packages("MASS", repos="http://cran.us.r-project.org")'
          Rscript -e 'install.packages("momentchi2", repos="http://cran.us.r-project.org")'
          Rscript -e 'install.packages("gert", repos="http://cran.us.r-project.org")'
          Rscript -e 'install.packages("devtools", repos="http://cran.us.r-project.org")'
          Rscript -e 'devtools::install_github("Diviyan-Kalainathan/RCIT")'
          Rscript -e 'install.packages("https://cran.r-project.org/src/contrib/Archive/SID/SID_1.0.tar.gz")'
      
      - name: Install Python Dependencies  
        run: |
          poetry install -E plotting -E causalml -E rpy2

      - name: Build
        run: |
          # sphinx-multiversion invokes git internally. Its call to "git rev-parse --show-toplevel" throws the
          # following error: "fatal: detected dubious ownership in repository at '/__w/dowhy/dowhy'"
          # The following command avoids this.
          git config --global --add safe.directory /__w/dowhy/dowhy
          ./docs/generate_docs.sh
          
      - name: Commit and push to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dowhy-docs
