name: Build Docs (CI)

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/docs-ci.yml"
      - "dowhy/**"
      - "docs/**"
      - "pyproject.toml"
      - "uv.lock"

jobs:
  docs:
    runs-on: ubuntu-24.04
    container:
      image: "ghcr.io/${{ github.repository_owner }}/dowhy-docs-generation:latest"
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Python Dependencies
        run: uv sync --extra plotting --extra pydot --extra pygraphviz --extra econml --group docs

      - run: git config --global --add safe.directory /__w/dowhy/dowhy

      - name: Build
        run: ./docs/generate_docs.sh
