name: Build Docs (CI)

on:
  pull_request:
    branches: [main]
    paths:
      - ".github/workflows/docs-ci.yml"
      - "dowhy/**"
      - "docs/**"
      - "pyproject.toml"
      - "poetry.lock"

jobs:
  docs:
    runs-on: ubuntu-latest
    container:
      image: "ghcr.io/${{ github.repository_owner }}/dowhy-docs-generation:latest"
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      # Reattach to a branch so that we can build docs on the branch
      - name: reattach HEAD to Head Ref
        run: git checkout "$(echo ${{ github.head_ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: github.head_ref != ''
      - name: reattach HEAD to Ref
        run: git checkout "$(echo ${{ github.ref }} | sed -E 's|refs/[a-zA-Z]+/||')"
        if: github.head_ref == ''

      - name: Install Python Dependencies
        run: poetry install -E plotting -E causalml -E econml -E pydot --with docs

      - name: Build
        run: |
          # sphinx-multiversion invokes git internally. Its call to "git rev-parse --show-toplevel" throws the
          # following error: "fatal: detected dubious ownership in repository at '/__w/dowhy/dowhy'"
          # The following command avoids this.
          git config --global --add safe.directory /__w/dowhy/dowhy
          ./docs/generate_docs.sh